name: Build

on:
  - push
  - workflow_dispatch

env:
  BUILD_CONFIGURATION: Release

jobs:
  Windows:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3

    - name: Get current date
      id: date
      run: echo "::set-output name=CurrentDate::$(date +'%Y-%m-%d')"

    - name: Get commit hash
      id: vars
      run: echo "::set-output name=ShortHash::$(git rev-parse --short=7 HEAD)"

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.1.3

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        nuget restore "Cavern.sln"
        nuget restore "Cavern.Format/Cavern.Format.csproj"
        nuget restore "CavernSamples/CavernSamples.sln"

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} "Cavern.sln"
        msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} "CavernSamples/CavernSamples.sln"

    - name: Build CavernizeCLI
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        dotnet build "CavernSamples/CavernizeCLI/CavernizeCLI.csproj" --configuration ${{env.BUILD_CONFIGURATION}}

    - name: Run tests
      continue-on-error: true
      run: |
        dotnet test Tests/Test.Cavern/Test.Cavern.csproj --no-build --configuration Release --verbosity normal
        dotnet test Tests/Test.Cavern.Format/Test.Cavern.Format.csproj --no-build --configuration Release --verbosity normal
        dotnet test Tests/Test.Cavern.QuickEQ/Test.Cavern.QuickEQ.csproj --no-build --configuration Release --verbosity normal

    - name: Download base build
      shell: powershell
      run: |
        Invoke-WebRequest -Method Get -Uri "https://cavern.sbence.hu/content/downloads/cavern64.zip" -OutFile cavern64.zip -UseBasicParsing
        mkdir build/Release
        7z x -obuild/Release cavern64.zip
        Remove-Item -Path "cavern64.zip"

    - name: Collect artifacts
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        copy "Cavern.QuickEQ/bin/Release/netstandard2.1/Cavern.dll" "build/Release/Cavern_Data/Managed/Cavern.dll"
        copy "Cavern.QuickEQ/bin/Release/netstandard2.1/Cavern.QuickEQ.dll" "build/Release/Cavern_Data/Managed/Cavern.QuickEQ.dll"
        copy "Cavern.Format/bin/Release/netstandard2.1/Cavern.Format.dll" "build/Release/Cavern_Data/Managed/Cavern.Format.dll"
        copy "Cavern.QuickEQ/bin/Release/CavernAmp.dll" "build/Release/Cavern_Data/Plugins/x86_64/CavernAmp.dll"
        New-Item -ItemType Directory -Path "build/Release/Tools/CavernizeCLI" -Force
        New-Item -ItemType Directory -Path "build/Release/Tools/CavernizeGUI" -Force
        Copy-Item -Path "CavernSamples/CavernizeCLI/bin/Release/net8.0/*" -Destination "build/Release/Tools/CavernizeCLI/" -Recurse
        Copy-Item -Path "CavernSamples/CavernizeGUI/bin/Release/net8.0-windows/*" -Destination "build/Release/Tools/CavernizeGUI/" -Recurse

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: "Cavern-Win64_${{steps.date.outputs.CurrentDate}}@${{steps.vars.outputs.ShortHash}}"
        path: "build/Release/"

    - name: Compress artifacts
      uses: vimtor/action-zip@v1
      with:
        files: "build/Release/"
        dest: "build/Cavern-Win64.zip"

    - name: Upload Windows artifact for release
      uses: actions/upload-artifact@v4
      with:
        name: "windows-zip"
        path: "build/Cavern-Win64.zip"

  macOS:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Get current date
      id: date
      run: echo "CurrentDate=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

    - name: Get commit hash
      id: vars
      run: echo "ShortHash=$(git rev-parse --short=7 HEAD)" >> $GITHUB_OUTPUT

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore Cavern.sln

    - name: Build
      run: dotnet build Cavern.sln --configuration ${{env.BUILD_CONFIGURATION}} --no-restore

    - name: Build CavernizeCLI
      run: dotnet build CavernSamples/CavernizeCLI/CavernizeCLI.csproj --configuration ${{env.BUILD_CONFIGURATION}}

    - name: Run tests
      continue-on-error: true
      run: |
        dotnet test Tests/Test.Cavern/Test.Cavern.csproj --no-build --configuration Release --verbosity normal
        dotnet test Tests/Test.Cavern.Format/Test.Cavern.Format.csproj --no-build --configuration Release --verbosity normal
        dotnet test Tests/Test.Cavern.QuickEQ/Test.Cavern.QuickEQ.csproj --no-build --configuration Release --verbosity normal

    - name: Collect artifacts
      run: |
        mkdir -p build/Release/macOS
        cp Cavern/bin/Release/netstandard2.1/Cavern.dll build/Release/macOS/
        cp Cavern.QuickEQ/bin/Release/netstandard2.1/Cavern.QuickEQ.dll build/Release/macOS/
        cp Cavern.Format/bin/Release/netstandard2.1/Cavern.Format.dll build/Release/macOS/
        cp Cavern.QuickEQ.Format/bin/Release/netstandard2.1/Cavern.QuickEQ.Format.dll build/Release/macOS/
        mkdir -p build/Release/macOS/Tools
        cp -r CavernSamples/CavernizeCLI/bin/Release/net8.0 build/Release/macOS/Tools/CavernizeCLI/

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: "Cavern-macOS_${{steps.date.outputs.CurrentDate}}@${{steps.vars.outputs.ShortHash}}"
        path: "build/Release/macOS/"

    - name: Compress artifacts
      run: |
        cd build/Release
        zip -r ../Cavern-macOS.zip macOS/

    - name: Upload macOS artifact for release
      uses: actions/upload-artifact@v4
      with:
        name: "macos-zip"
        path: "build/Cavern-macOS.zip"

  release:
    needs: [Windows, macOS]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' || github.event_name == 'workflow_dispatch'

    steps:
    - uses: actions/checkout@v3

    - name: Get current date
      id: date
      run: echo "CurrentDate=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

    - name: Get commit hash
      id: vars
      run: echo "ShortHash=$(git rev-parse --short=7 HEAD)" >> $GITHUB_OUTPUT

    - name: Download Windows artifact
      uses: actions/download-artifact@v4
      with:
        name: "windows-zip"
        path: "artifacts/"

    - name: Download macOS artifact
      uses: actions/download-artifact@v4
      with:
        name: "macos-zip"
        path: "artifacts/"

    - name: GitHub pre-release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{secrets.GITHUB_TOKEN}}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Cavern @${{steps.vars.outputs.ShortHash}}[${{steps.date.outputs.CurrentDate}}]"
        files: "artifacts/*.zip"
